ElderLists/ElderLists/Controllers/CharactersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ElderListsDatabase;
using ElderListsDatabase.Models;
using ElderLists.Models;
using Microsoft.AspNet.Identity;
using ElderLists.Extensions;

namespace ElderLists.Controllers
{
    public class CharactersController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        // GET: Characters
        public async Task<ActionResult> Index()
        {
            var characters = await db.GetAccessableCharacters(User.IsInRole("Admin"), User.IsInRole("Moderator"))
                .OrderByDescending(c => c.LastChanged)
                .Include(c => c.Race)
                .Select(c => new CharacterListItemViewModel
                {
                    Id = c.Id,
                    AuthorId = c.UserId,
                    Author = c.User.UserName,
                    Name = c.Name,
                    IsPublic = c.IsPublic,
                    LastChanged = c.LastChanged,
                    Class = c.Class.Name,
                    Race = c.Race.SpecialName == null ?
                        c.Race.CommonName : (c.Race.CommonName.Length < c.Race.SpecialName.Length ?
                            c.Race.CommonName : c.Race.SpecialName),
                    HaveIssues = c.Issues.Where(i => !(i.IsAccepted && i.IsResolved)).Any(),
                }).ToListAsync();

            return View(characters);
        }

        // GET: Characters/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Character character = await db.Characters.FindAsync(id);
            if (character == null)
                return HttpNotFound();

            bool loadIssue = User.Identity.GetUserId<int>() == character.UserId || User.IsInRole("Moderator") || User.IsInRole("Admin");
            return View(new CharacterDetailsViewModel(character, loadIssue));
        }

        [Authorize]
        public async Task<ActionResult> My()
        {
            int userId = User.Identity.GetUserId<int>();
            var characters = db.Characters
                .Where(c => c.UserId == userId)
                .OrderByDescending(c => c.LastChanged)
                .Include(c => c.Race)
                .Select(c => new CharacterListItemViewModel
                {
                    Id = c.Id,
                    Name = c.Name,
                    Race = c.Race.SpecialName == null ? c.Race.CommonName : (c.Race.CommonName.Length < c.Race.SpecialName.Length ? c.Race.CommonName : c.Race.SpecialName),
                    Class = c.Class.Name,
                    LastChanged = c.LastChanged,
                    IsPublic = c.IsPublic,
                    HaveIssues = c.Issues.Where(i => !(i.IsAccepted && i.IsResolved)).Any(),
                });
            return View(await characters.ToListAsync());
        }

        [Authorize(Roles = "Moderator,Admin")]
        public async Task<ActionResult> Moderation()
        {
            if (!(await db.IsUserInRole(User.Identity.GetUserId<int>(), "Moderator") || await db.IsUserInRole(User.Identity.GetUserId<int>(), "Admin")))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            var characters = db.Characters
                .Where(c => c.Issues.Where(i => !(i.IsAccepted && i.IsResolved)).Any())
                .OrderByDescending(c => c.LastChanged)
                .Select(c => new
                {
                    Character = c,
                    Issue = c.Issues.Where(i => !(i.IsAccepted && i.IsResolved)).FirstOrDefault()
                })
                .Select(ci => new ModerationCharacterListItemViewModel
                {
                    Id = ci.Character.Id,
                    Name = ci.Character.Name,
                    LastChanged = ci.Character.LastChanged,
                    AuthorId = ci.Character.UserId,
                    Author = ci.Character.User.UserName,
                    ModeratorId = ci.Issue.UserId,
                    Moderator = ci.Issue.User.UserName,
                    IsAccepted = ci.Issue.IsAccepted,
                    IsResolved = ci.Issue.IsResolved,
                    LastReview = ci.Issue.LastReview,
                });
            return View(await characters.ToListAsync());
        }

        // GET: Characters/Create
        [Authorize(Roles = "User")]
        public async Task<ActionResult> Create()
        {
            if (!await db.IsUserInRole(User.Identity.GetUserId<int>(), "User"))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            ViewBag.AlignmentId = new SelectList(db.Alignments, "Id", "Name");
            ViewBag.ClassId = new SelectList(db.Classes.OrderBy(o => o.Name), "Id", "Name");
            ViewBag.GenderId = new SelectList(db.Genders, "Id", "Name");
            ViewBag.RaceId = CreateRacesSelectList();

            return View();
        }

        // POST: Characters/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User")]
        public async Task<ActionResult> Create([Bind(Include = "Name,LastChanged,IsPublic,RaceId,GenderId,AbsoluteAge," +
            "RelativeAge,Appearance,CombatGear,CommonGear,SpecialSigns,AlignmentId,Personality,Vices,Virtues,Occupation," +
            "ClassId,CombatTactics,SkillsSource")] CharacterEditViewModel model)
        {
            if (!await db.IsUserInRole(User.Identity.GetUserId<int>(), "User"))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            if (ModelState.IsValid)
            {
                var character = await AddOrUpdateDatabaseModelAsync(model);
                await UpdateUserLastAction();
                return RedirectToAction("Details", new { id = character.Id });
            }

            ViewBag.AlignmentId = new SelectList(db.Alignments, "Id", "Name", model.AlignmentId);
            ViewBag.ClassId = new SelectList(db.Classes.OrderBy(o => o.Name), "Id", "Name", model.ClassId);
            ViewBag.GenderId = new SelectList(db.Genders, "Id", "Name", model.GenderId);
            ViewBag.RaceId = CreateRacesSelectList(model.RaceId);

            return View(model);
        }

        // GET: Characters/Edit/5
        [Authorize]
        [Authorize(Roles = "User")]
        public async Task<ActionResult> Edit(int id)
        {
            if (!await db.IsUserInRole(User.Identity.GetUserId<int>(), "User"))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            Character character = await db.Characters.FindAsync(id);
            if (character == null)
                return HttpNotFound();

            ViewBag.AlignmentId = new SelectList(db.Alignments, "Id", "Name", character.AlignmentId);
            ViewBag.ClassId = new SelectList(db.Classes.OrderBy(o => o.Name), "Id", "Name", character.ClassId);
            ViewBag.GenderId = new SelectList(db.Genders, "Id", "Name", character.GenderId);
            ViewBag.RaceId = CreateRacesSelectList(character.RaceId);

            return View(new CharacterEditViewModel(character));
        }

        // POST: Characters/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User")]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,UserId,IsPublic,RaceId,GenderId,AbsoluteAge," +
            "RelativeAge,Appearance,CombatGear,CommonGear,SpecialSigns,AlignmentId,Personality,Vices,Virtues," +
            "Occupation,ClassId,CombatTactics,SkillsSource")] CharacterEditViewModel model)
        {
            if (!await db.IsUserInRole(User.Identity.GetUserId<int>(), "User"))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            if (ModelState.IsValid)
            {

                var character = await AddOrUpdateDatabaseModelAsync(model);
                await UpdateVisibility(character);
                await UpdateUserLastAction();
                return RedirectToAction("Details", new { id = character.Id });
            }

            ViewBag.AlignmentId = new SelectList(db.Alignments, "Id", "Name", model.AlignmentId);
            ViewBag.ClassId = new SelectList(db.Classes.OrderBy(o => o.Name), "Id", "Name", model.ClassId);
            ViewBag.GenderId = new SelectList(db.Genders, "Id", "Name", model.GenderId);
            ViewBag.RaceId = CreateRacesSelectList(model.RaceId);

            return View(model);
        }

        // GET: Characters/Edit/5
        [Authorize(Roles = "Moderator")]
        public async Task<ActionResult> Fix(int id)
        {
            if (!await db.IsUserInRole(User.Identity.GetUserId<int>(), "Moderator"))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            Character character = await db.Characters.FindAsync(id);
            if (character == null)
                return HttpNotFound();

            if (User.Identity.GetUserId<int>() == character.UserId)
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            ViewBag.AlignmentId = new SelectList(db.Alignments, "Id", "Name", character.AlignmentId);
            ViewBag.ClassId = new SelectList(db.Classes.OrderBy(o => o.Name), "Id", "Name", character.ClassId);

ElderLists/ElderLists/Controllers/ModerationController.cs
using ElderLists.Models;
using ElderListsDatabase;
using ElderListsDatabase.Models.Identity;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ElderLists.Controllers
{
    public class ModerationController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        [Authorize]
        public async Task<ActionResult> Accept(int id)
        {
            var issue = await db.Issues.FindAsync(id);
            if (issue == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            issue.IsAccepted = true;
            await db.SaveChangesAsync();
            return Redirect(Request.UrlReferrer.ToString());
        }

        [Authorize(Roles = "Moderator")]
        public async Task<ActionResult> Resolve(int id)
        {
            var issue = await db.Issues.FindAsync(id);
            if (issue == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            if (issue.UserId != User.Identity.GetUserId<int>())
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            issue.IsResolved = true;
            await db.SaveChangesAsync();
            return Redirect(Request.UrlReferrer.ToString());
        }

        [Authorize(Roles = "Moderator,Admin")]
        public async Task<ActionResult> Close(int id)
        {
            var issue = await db.Issues.FindAsync(id);
            if (issue == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            if (issue.UserId == User.Identity.GetUserId<int>() || User.IsInRole("Admin"))
            {
                issue.IsAccepted = true;
                issue.IsResolved = true;
                await db.SaveChangesAsync();
                return Redirect(Request.UrlReferrer.ToString());
            }
            else
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Charge(int id)
        {
            var user = db.Users.Find(id);
            if (user == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            int roleId = await db.Roles.Where(r => r.Name == "Moderator").Select(r => r.Id).SingleAsync();
            if (user.Roles.Where(ur => ur.RoleId == roleId).Any())
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            db.UserRoles.Add(new UserRole { RoleId = roleId, UserId = id });
            await db.SaveChangesAsync();
            return Redirect(Request.UrlReferrer.ToString());
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Discharge(int id)
        {
            var user = db.Users.Find(id);
            if (user == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            int roleId = await db.Roles.Where(r => r.Name == "Moderator").Select(r => r.Id).SingleAsync();
            var userRole = user.Roles.Where(ur => ur.RoleId == roleId).SingleOrDefault();
            if (userRole == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            if (db.Issues.Where(i => !(i.IsAccepted && i.IsResolved) && i.UserId == id).Any())
            {
                var otherModerators = db.Users
                    .Where(u => u.Roles.Select(ur => ur.RoleId).Contains(roleId))
                    .Except(db.Users.Where(u => u.Id == id));
                if (otherModerators.Any())
                    ViewBag.UserId = new SelectList(otherModerators, "Id", "UserName");

                return View(new DischargeViewModel
                {
                    OriginalUserId = id,
                    OriginalUser = user.UserName,
                    ReturnUrl = Request.UrlReferrer.ToString(),
                });
            }
            else
            {
                db.UserRoles.Remove(userRole);
                await db.SaveChangesAsync();
                return Redirect(Request.UrlReferrer.ToString());
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> DischargeRedirect(DischargeViewModel model)
        {
            var issues = await db.Issues
                    .Where(i => !(i.IsAccepted && i.IsResolved) && i.UserId == model.OriginalUserId)
                    .ToListAsync();

            foreach (var item in issues)
                item.UserId = model.UserId;
            await db.SaveChangesAsync();

            await RemoveModerator(model.OriginalUserId);
            return Redirect(model.ReturnUrl);
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> DischargeClose(int id, string returnUrl)
        {
            var issues = await db.Issues
                    .Where(i => !(i.IsAccepted && i.IsResolved) && i.UserId == id)
                    .ToListAsync();

            foreach (var item in issues)
            {
                item.IsAccepted = true;
                item.IsResolved = true;
            }
            await db.SaveChangesAsync();

            await RemoveModerator(id);
            return Redirect(returnUrl);
        }

        private async Task RemoveModerator(int userId)
        {
            int roleId = await db.Roles
                .Where(r => r.Name == "Moderator")
                .Select(r => r.Id)
                .SingleAsync();
            var userRole = await db.UserRoles
                .Where(ur => ur.RoleId == roleId && ur.UserId == userId)
                .SingleAsync();
            db.UserRoles.Remove(userRole);
            await db.SaveChangesAsync();
        }
    }
}

ElderLists/ElderLists/Views/Characters/About.cshtml
@model ElderLists.Models.CharactersAboutViewModel
@{
    ViewBag.Title = "О персонажах";
}

<h2>@ViewBag.Title</h2>

<div>
    <div>
        <h3>Мировоззрение</h3>
        <p>При создании персонажа используется система мировоззрений Dungeons & Dragons.</p>
        <p>
            Мировоззрение отражает этические и моральные норма персонажа,
            помогая мастеру спрогнозировать его поведение в различных ситуациях.
        </p>
        <p><a class="btn btn-default" href="https://ru.wikipedia.org/wiki/%D0%9C%D0%B8%D1%80%D0%BE%D0%B2%D0%BE%D0%B7%D0%B7%D1%80%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B2_Dungeons_%26_Dragons" target="_blank">Wikipedia (ru) &raquo;</a></p>
    </div>

    <div>
        <h3>Расы</h3>
        <p>Список рас при создании персонажа основан на игровых расах Elder Scrolls Online.</p>
        <table class="table">
            <tr>
                <th>Раса</th>
                <th>Ссылки</th>
            </tr>
            @foreach (var item in Model.Races)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>
                        @foreach (var link in item.Links)
                        {
                            <a class="btn btn-default" href="@link.Url" target="_blank">@link.ResourceName &raquo;</a>
                        }
                    </td>
                </tr>
            }
        </table>
    </div>

    <div>
        <h3>Классы</h3>
        <p>Класс отражает общую направленность навыков персонажа.</p>
        <p>Список классов был позаимствован из The Elder Scrolls 3: Morrowind и The Elder Scrolls 4: Oblivion.</p>
        <table class="table">
            <tr>
                <th class="col-md-2">Класс</th>
                <th class="col-md-2">Тип</th>
                <th class="col-md-8">Описание</th>
            </tr>
            @foreach (var item in Model.Classes)
            {
                <tr>
                    <td class="col-md-2">@item.Name</td>
                    <td class="col-md-2">@item.TypeName</td>
                    <td class="col-md-8">@item.Description</td>
                </tr>
            }
        </table>
    </div>
</div>

ElderLists/ElderLists/Views/Characters/AlignmentDetails.cshtml
@model IEnumerable<ElderLists.Models.LinkViewModel>

@if (Model.Any())
{
    <div class="row">
        <div class="form-control-static col-md-2">
            <label>Подробнее:</label>
        </div>
        <div class="col-md-10">
            @foreach (var item in Model)
            {
                <a class="btn btn-default" href="@item.Url" target="_blank">@item.ResourceName &raquo;</a>
            }
        </div>
    </div>
}

ElderLists/ElderLists/Views/Characters/ClassDetails.cshtml
@model ElderLists.Models.ClassViewModel

<div>
    <div class="col-md-3">
        <strong>@Html.DisplayNameFor(model => model.TypeName)</strong>
        <p>@Html.DisplayFor(model => model.TypeName)</p>
    </div>
    <div class="col-md-9">
        <strong>@Html.DisplayNameFor(model => model.Description)</strong>
        <p>@Html.DisplayFor(model => model.Description)</p>
    </div>
</div>

ElderLists/ElderLists/Views/Characters/Index.cshtml
@model IEnumerable<ElderLists.Models.CharacterListItemViewModel>

@{
    ViewBag.Title = "Персонажи";
    bool access = User.IsInRole("Moderator") || User.IsInRole("Admin");
    bool user = User.IsInRole("User");
}

<h2>@ViewBag.Title</h2>

@if (User.Identity.IsAuthenticated)
{
<p>
    @if (user)
    {
        @Html.ActionLink("Новый персонаж", "Create", "Characters", routeValues: null, htmlAttributes: new { @class = "btn btn-default" })
    }
    @Html.ActionLink("Мои персонажи", "My", "Characters", routeValues: null, htmlAttributes: new { @class = "btn btn-default" })
    @if (access)
    {
        @Html.ActionLink("Персонажи на модерации", "Moderation", "Characters", routeValues: null, htmlAttributes: new { @class = "btn btn-default" })
    }
</p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Race)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Class)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
        @if (access)
        {
            <th>
                @Html.DisplayNameFor(model => model.IsPublic)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HaveIssues)
            </th>
        }
        <th>
            @Html.DisplayNameFor(model => model.LastChanged)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Race)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Class)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Author)
        </td>
        @if (access)
        {
            <td>
                @Html.DisplayFor(modelItem => item.IsPublic)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HaveIssues)
            </td>
        }
        <td>
            @Html.DisplayFor(modelItem => item.LastChanged)
        </td>
        <th>
            @Html.ActionLink("Подробнее", "Details", "Characters", routeValues: new { id = item.Id }, htmlAttributes: new { @class = "btn btn-default" })
            @Html.ActionLink("Об авторе", "Details", "Users", routeValues: new { id = item.AuthorId }, htmlAttributes: new { @class = "btn btn-default" })
        </th>
    </tr>
}

</table>

ElderLists/ElderLists/Views/Characters/Moderation.cshtml
@model IEnumerable<ElderLists.Models.ModerationCharacterListItemViewModel>
@{
    ViewBag.Title = "Персонажи на модерации";
}

<h2>@ViewBag.Title</h2>

<p>
    @if (User.IsInRole("User"))
    {
        @Html.ActionLink("Новый персонаж", "Create", "Characters", routeValues: null, htmlAttributes: new { @class = "btn btn-default" })
    }
    @Html.ActionLink("Мои персонажи", "My", "Characters", routeValues: null, htmlAttributes: new { @class = "btn btn-default" })
    @Html.ActionLink("Все персонажи", "Index", "Characters", routeValues: null, htmlAttributes: new { @class = "btn btn-default" })
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Author)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Moderator)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastReview)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastChanged)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Author)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Moderator)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastReview)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastChanged)
            </td>
            <th>
                @Html.ActionLink("Подробнее", "Details", "Characters", routeValues: new { id = item.Id }, htmlAttributes: new { @class = "btn btn-default" })
                @Html.ActionLink("Об авторе", "Details", "Users", routeValues: new { id = item.AuthorId }, htmlAttributes: new { @class = "btn btn-default" })
                @Html.ActionLink("О модераторе", "Details", "Users", routeValues: new { id = item.ModeratorId }, htmlAttributes: new { @class = "btn btn-default" })
            </th>
        </tr>
    }

</table>

ElderLists/ElderLists/Views/Characters/My.cshtml
@model IEnumerable<ElderLists.Models.CharacterListItemViewModel>

@{
    ViewBag.Title = "Мои персонажи";
}

<h2>@ViewBag.Title</h2>
@if (User.Identity.IsAuthenticated)
{
    <p>
        @Html.ActionLink("Новый персонаж", "Create", "Characters", routeValues: null, htmlAttributes: new { @class = "btn btn-default" })
        @Html.ActionLink("Все персонажи", "Index", "Characters", routeValues: null, htmlAttributes: new { @class = "btn btn-default" })
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Race)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Class)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsPublic)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HaveIssues)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastChanged)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Race)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Class)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsPublic)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HaveIssues)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastChanged)
            </td>
            <th>
                @Html.ActionLink("Подробнее", "Details", "Characters", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-default" })
            </th>
        </tr>
    }

</table>

ElderLists/ElderLists/Views/Characters/RaceDetails.cshtml
@model IEnumerable<ElderLists.Models.LinkViewModel>

@if (Model.Any())
{
    <div class="row">
        <div class="form-control-static col-md-2">
            <label>Подробнее:</label>
        </div>
        <div class="col-md-10">
            @foreach (var item in Model)
            {
                <a class="btn btn-default" href="@item.Url" target="_blank">@item.ResourceName &raquo;</a>
            }
        </div>
    </div>
}

ElderLists/ElderLists/Views/Characters/Review.cshtml
@model ElderLists.Models.CharacterReviewViewModel
@using ElderLists.Extensions

@{
    ViewBag.Title = "Замечание";
}

<h2>@ViewBag.Title</h2>
<hr />

@Html.Partial("CharacterDetails", Model)

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Id)
    
    <div class="form-horizontal">
        <div class="form-group">
            <h3>Замечание</h3>
            @Html.ValidationSummary("", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.IssueText, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.IssueText, new { htmlAttributes = new { @class = "form-control", @rows = 4 } })
                    @Html.ValidationMessageFor(model => model.IssueText, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-4 form-control-static">
                    @Html.DisplayDescriptionFor(model => model.IssueText)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsPrivateLocked, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.IsPrivateLocked)
                    @Html.ValidationMessageFor(model => model.IsPrivateLocked, "", new { @class = "text-danger" })
       
                </div>
                <div class="col-md-4 form-control-static">
                    @Html.DisplayDescriptionFor(model => model.IsPrivateLocked)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.IsResolved, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.IsResolved)
                    @Html.ValidationMessageFor(model => model.IsResolved, "", new { @class = "text-danger" })

                </div>
                <div class="col-md-4 form-control-static">
                    @Html.DisplayDescriptionFor(model => model.IsResolved)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2">
                    @Html.ActionLink("Назад", "Details", "Characters", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-default" })
                    <input type="submit" value="Сохранить" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
    
}