ElderLists/ElderLists/Controllers/CharactersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ElderListsDatabase;
using ElderListsDatabase.Models;
using ElderLists.Models;
using Microsoft.AspNet.Identity;
using ElderLists.Extensions;

namespace ElderLists.Controllers
{
    public class CharactersController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        // GET: Characters
        public async Task<ActionResult> Index()
        {
            var characters = await db.GetAccessableCharacters(User.IsInRole("Admin"), User.IsInRole("Moderator"))
                .OrderByDescending(c => c.LastChanged)
                .Include(c => c.Race)
                .Select(c => new CharacterListItemViewModel
                {
                    Id = c.Id,
                    AuthorId = c.UserId,
                    Author = c.User.UserName,
                    Name = c.Name,
                    IsPublic = c.IsPublic,
                    LastChanged = c.LastChanged,
                    Class = c.Class.Name,
                    Race = c.Race.SpecialName == null ?
                        c.Race.CommonName : (c.Race.CommonName.Length < c.Race.SpecialName.Length ?
                            c.Race.CommonName : c.Race.SpecialName),
                    HaveIssues = c.Issues.Where(i => !(i.IsAccepted && i.IsResolved)).Any(),
                }).ToListAsync();

            return View(characters);
        }

        // GET: Characters/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            Character character = await db.Characters.FindAsync(id);
            if (character == null)
                return HttpNotFound();

            bool loadIssue = User.Identity.GetUserId<int>() == character.UserId || User.IsInRole("Moderator") || User.IsInRole("Admin");
            return View(new CharacterDetailsViewModel(character, loadIssue));
        }

        [Authorize]
        public async Task<ActionResult> My()
        {
            int userId = User.Identity.GetUserId<int>();
            var characters = db.Characters
                .Where(c => c.UserId == userId)
                .OrderByDescending(c => c.LastChanged)
                .Include(c => c.Race)
                .Select(c => new CharacterListItemViewModel
                {
                    Id = c.Id,
                    Name = c.Name,
                    Race = c.Race.SpecialName == null ? c.Race.CommonName : (c.Race.CommonName.Length < c.Race.SpecialName.Length ? c.Race.CommonName : c.Race.SpecialName),
                    Class = c.Class.Name,
                    LastChanged = c.LastChanged,
                    IsPublic = c.IsPublic,
                    HaveIssues = c.Issues.Where(i => !(i.IsAccepted && i.IsResolved)).Any(),
                });
            return View(await characters.ToListAsync());
        }

        [Authorize(Roles = "Moderator,Admin")]
        public async Task<ActionResult> Moderation()
        {
            if (!(await db.IsUserInRole(User.Identity.GetUserId<int>(), "Moderator") || await db.IsUserInRole(User.Identity.GetUserId<int>(), "Admin")))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            var characters = db.Characters
                .Where(c => c.Issues.Where(i => !(i.IsAccepted && i.IsResolved)).Any())
                .OrderByDescending(c => c.LastChanged)
                .Select(c => new
                {
                    Character = c,
                    Issue = c.Issues.Where(i => !(i.IsAccepted && i.IsResolved)).FirstOrDefault()
                })
                .Select(ci => new ModerationCharacterListItemViewModel
                {
                    Id = ci.Character.Id,
                    Name = ci.Character.Name,
                    LastChanged = ci.Character.LastChanged,
                    AuthorId = ci.Character.UserId,
                    Author = ci.Character.User.UserName,
                    ModeratorId = ci.Issue.UserId,
                    Moderator = ci.Issue.User.UserName,
                    IsAccepted = ci.Issue.IsAccepted,
                    IsResolved = ci.Issue.IsResolved,
                    LastReview = ci.Issue.LastReview,
                });
            return View(await characters.ToListAsync());
        }

        // GET: Characters/Create
        [Authorize(Roles = "User")]
        public async Task<ActionResult> Create()
        {
            if (!await db.IsUserInRole(User.Identity.GetUserId<int>(), "User"))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            ViewBag.AlignmentId = new SelectList(db.Alignments, "Id", "Name");
            ViewBag.ClassId = new SelectList(db.Classes.OrderBy(o => o.Name), "Id", "Name");
            ViewBag.GenderId = new SelectList(db.Genders, "Id", "Name");
            ViewBag.RaceId = CreateRacesSelectList();

            return View();
        }

        // POST: Characters/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User")]
        public async Task<ActionResult> Create([Bind(Include = "Name,LastChanged,IsPublic,RaceId,GenderId,AbsoluteAge," +
            "RelativeAge,Appearance,CombatGear,CommonGear,SpecialSigns,AlignmentId,Personality,Vices,Virtues,Occupation," +
            "ClassId,CombatTactics,SkillsSource")] CharacterEditViewModel model)
        {
            if (!await db.IsUserInRole(User.Identity.GetUserId<int>(), "User"))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            if (ModelState.IsValid)
            {
                var character = await AddOrUpdateDatabaseModelAsync(model);
                await UpdateUserLastAction();
                return RedirectToAction("Details", new { id = character.Id });
            }

            ViewBag.AlignmentId = new SelectList(db.Alignments, "Id", "Name", model.AlignmentId);
            ViewBag.ClassId = new SelectList(db.Classes.OrderBy(o => o.Name), "Id", "Name", model.ClassId);
            ViewBag.GenderId = new SelectList(db.Genders, "Id", "Name", model.GenderId);
            ViewBag.RaceId = CreateRacesSelectList(model.RaceId);

            return View(model);
        }

        // GET: Characters/Edit/5
        [Authorize]
        [Authorize(Roles = "User")]
        public async Task<ActionResult> Edit(int id)
        {
            if (!await db.IsUserInRole(User.Identity.GetUserId<int>(), "User"))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            Character character = await db.Characters.FindAsync(id);
            if (character == null)
                return HttpNotFound();

            ViewBag.AlignmentId = new SelectList(db.Alignments, "Id", "Name", character.AlignmentId);
            ViewBag.ClassId = new SelectList(db.Classes.OrderBy(o => o.Name), "Id", "Name", character.ClassId);
            ViewBag.GenderId = new SelectList(db.Genders, "Id", "Name", character.GenderId);
            ViewBag.RaceId = CreateRacesSelectList(character.RaceId);

            return View(new CharacterEditViewModel(character));
        }

        // POST: Characters/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User")]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,UserId,IsPublic,RaceId,GenderId,AbsoluteAge," +
            "RelativeAge,Appearance,CombatGear,CommonGear,SpecialSigns,AlignmentId,Personality,Vices,Virtues," +
            "Occupation,ClassId,CombatTactics,SkillsSource")] CharacterEditViewModel model)
        {
            if (!await db.IsUserInRole(User.Identity.GetUserId<int>(), "User"))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            if (ModelState.IsValid)
            {

                var character = await AddOrUpdateDatabaseModelAsync(model);
                await UpdateVisibility(character);
                await UpdateUserLastAction();
                return RedirectToAction("Details", new { id = character.Id });
            }

            ViewBag.AlignmentId = new SelectList(db.Alignments, "Id", "Name", model.AlignmentId);
            ViewBag.ClassId = new SelectList(db.Classes.OrderBy(o => o.Name), "Id", "Name", model.ClassId);
            ViewBag.GenderId = new SelectList(db.Genders, "Id", "Name", model.GenderId);
            ViewBag.RaceId = CreateRacesSelectList(model.RaceId);

            return View(model);
        }

        // GET: Characters/Edit/5
        [Authorize(Roles = "Moderator")]
        public async Task<ActionResult> Fix(int id)
        {
            if (!await db.IsUserInRole(User.Identity.GetUserId<int>(), "Moderator"))
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            Character character = await db.Characters.FindAsync(id);
            if (character == null)
                return HttpNotFound();

            if (User.Identity.GetUserId<int>() == character.UserId)
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);

            ViewBag.AlignmentId = new SelectList(db.Alignments, "Id", "Name", character.AlignmentId);
            ViewBag.ClassId = new SelectList(db.Classes.OrderBy(o => o.Name), "Id", "Name", character.ClassId);

ElderLists/ElderLists/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ElderListsDatabase;
using ElderListsDatabase.Models.Identity;
using ElderLists.Models;
using Microsoft.AspNet.Identity;
using ElderLists.Extensions;

namespace ElderLists.Controllers
{
    public class UsersController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        public async Task<ActionResult> Index()
        {
            IQueryable<User> users = db.Users;
            if (!User.IsInRole("Admin"))
            {
                var userRoleId = await db.Roles.Where(r => r.Name == "User").Select(r => r.Id).SingleAsync();
                users = users.Where(u => u.Roles.Select(ur => ur.RoleId).Contains(userRoleId));
            }

            var list = await users
                .Include(u => u.Characters)
                .OrderByDescending(u => u.LastAction)
                .Select(u => new UserListItemViewModel()
                {
                    Id = u.Id,
                    UserName = u.UserName,
                    LastAction = u.LastAction,
                    Characters = u.Characters.Count,
                    HiddenCharacters = u.Characters.Where(c => !c.IsPublic).Count(),
                })
                .ToListAsync();

            return View(list);
        }

        
        public async Task<ActionResult> Moderators()
        {
            var moderatorId = await db.Roles
                .Where(r => r.Name == "Moderator")
                .Select(r => r.Id)
                .SingleAsync();

            var userRoles = await db.UserRoles
                .Where(ur => ur.RoleId == moderatorId)
                .Select(ur => ur.UserId)
                .Distinct()
                .ToListAsync();

            var users = await db.Users
                .Join(userRoles, u => u.Id, ur => ur, (u, ur) => new UserModeratorListItemViewModel
                {
                    Id = u.Id,
                    UserName = u.UserName,
                    Issues = u.Issues.Count,
                    OpenIssues = u.Issues.Where(i => !(i.IsAccepted && i.IsResolved)).Count(),
                    LastAction = u.LastAction,
                })
                .OrderByDescending(vm => vm.LastAction)
                .ToListAsync();

            return View(users);
        }

        [Authorize]
        public ActionResult My()
        {
            return RedirectToAction("Details", new { id = User.Identity.GetUserId<int>() });
        }

        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var user = await db.Users.Where(u => u.Id == id).SingleAsync();
            if (user == null)
                return HttpNotFound();

            var userRolesIds = user.Roles.Select(ur => ur.RoleId).ToList();

            var model = new UserDetailsViewModel
            {
                Id = user.Id,
                UserName = user.UserName,
                About = user.About,
                LastAction = user.LastAction,
                RegisterDate = user.RegisterDate,
                Email = user.IsEmailHidden && !User.IsInRole("Admin") ? null : user.Email,
                IsEmailHidden = user.IsEmailHidden,

                Roles = await db.Roles
                    .Where(r => userRolesIds.Contains(r.Id))
                    .OrderBy(r => r.ViewName)
                    .Select(r => r.ViewName)
                    .ToListAsync(),
                IsModerator = await db.IsUserInRole(user.Id, "Moderator"),
                IsUser = await db.IsUserInRole(user.Id, "User"),

                Characters = await UserCharactersListAsync(user.Id),
                Contacts = new UserContactsViewModel(user),
                Issues = await UserIssuesListAsync(user.Id),
            };

            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Charge(int id)
        {
            var user = await db.Users.Where(u => u.Id == id).SingleOrDefaultAsync();
            if (user == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var roleId = await db.Roles.Where(r => r.Name == "User").Select(r => r.Id).SingleAsync();

            if (user.Roles.Select(ur => ur.RoleId).Contains(roleId))
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            db.UserRoles.Add(new UserRole { UserId = id, RoleId = roleId });
            await db.SaveChangesAsync();

            return Redirect(Request.UrlReferrer.ToString());
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Discharge(int id)
        {
            var user = await db.Users.Where(u => u.Id == id).SingleOrDefaultAsync();
            if (user == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var roleId = await db.Roles.Where(r => r.Name == "User").Select(r => r.Id).SingleAsync();
            var userRole = user.Roles.Where(ur => ur.RoleId == roleId).SingleOrDefault();

            if (userRole == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            db.UserRoles.Remove(userRole);
            await db.Characters.Where(c => c.UserId == id).ForEachAsync(c => c.IsPublic = false);
            await db.SaveChangesAsync();

            return Redirect(Request.UrlReferrer.ToString());
        }

        private async Task<List<CharacterListItemViewModel>> UserCharactersListAsync(int userId)
        {
            bool userAdmin = User.IsInRole("Admin");
            bool userModerator = User.IsInRole("Moderator");

            var characters = await db.GetAccessableCharacters(userAdmin, userModerator, userId)
                .OrderByDescending(c => c.LastChanged)
                .Include(c => c.Race)
                
                .Select(c => new CharacterListItemViewModel
                {
                    Id = c.Id,
                    AuthorId = c.Id,
                    Name = c.Name,
                    IsPublic = c.IsPublic,
                    LastChanged = c.LastChanged,
                    Class = c.Class.Name,
                    Race = c.Race.SpecialName == null ? 
                        c.Race.CommonName : (c.Race.CommonName.Length < c.Race.SpecialName.Length ?
                            c.Race.CommonName : c.Race.SpecialName),
                    HaveIssues = c.Issues.Where(i => !(i.IsAccepted && i.IsResolved)).Any(),
                }).ToListAsync();


            return characters.Count == 0 ? null : characters;
        }

        private async Task<List<ModerationIssueListItemViewModel>> UserIssuesListAsync(int userId)
        {
            if (User.IsInRole("Moderator") || User.IsInRole("Admin"))
            {
                var issues = await db.Issues
                    .Where(i => i.UserId == userId)
                    .Include(i => i.Characters).Include(i => i.User)
                    .OrderByDescending(i => i.LastReview)
                    .ToListAsync();

                if (issues.Count != 0)
                    return issues
                        .Select(i => new ModerationIssueListItemViewModel(i))
                        .ToList();
            }
            return null;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ElderLists/ElderLists/Views/Users/Characters.cshtml
@model IEnumerable<ElderLists.Models.CharacterListItemViewModel>
@{ 
    bool access = User.IsInRole("Admin") || User.IsInRole("Moderator");
}


<h3>Персонажи</h3>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Race)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Class)
        </th>
        @if (access)
        {
            <th>
                @Html.DisplayNameFor(model => model.IsPublic)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HaveIssues)
            </th>
        }
        <th>
            @Html.DisplayNameFor(model => model.LastChanged)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Race)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Class)
            </td>
            @if (access)
            {
                <td>
                    @Html.DisplayFor(modelItem => item.IsPublic)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HaveIssues)
                </td>
            }
            <td>
                @Html.DisplayFor(modelItem => item.LastChanged)
            </td>
            <th>
                @Html.ActionLink("Подробнее", "Details", "Characters", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-default" })
            </th>
        </tr>
    }
</table>

ElderLists/ElderLists/Views/Users/Contacts.cshtml
@model ElderLists.Models.UserContactsViewModel
@using ElderLists.Extensions

@if (Model.Discord != null || Model.EsoUserId != null || Model.Telegram != null || Model.Skype != null)
{
<div class="form-horizontal">
    <h3>Контакты</h3>
    @if (Model.EsoUserId != null)
    {
        <div class="form-group">
            @Html.LabelFor(model => model.EsoUserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                <div class="form-control-static">
                    @Html.DisplayFor(model => model.EsoUserId)
                </div>
            </div>
        </div>
    }
    @if (Model.Discord != null)
    {
    <div class="form-group">
        @Html.LabelFor(model => model.Discord, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-6">
            <div class="form-control-static">
                @Html.DisplayFor(model => model.Discord)
            </div>
        </div>
    </div>
    }
    @if (Model.Telegram != null)
    {
        <div class="form-group">
            @Html.LabelFor(model => model.Telegram, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                <div class="form-control-static">
                    @Html.DisplayFor(model => model.Telegram)
                </div>
            </div>
        </div>
    }
    @if (Model.Skype != null)
    {
        <div class="form-group">
            @Html.LabelFor(model => model.Skype, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                <div class="form-control-static">
                    @Html.DisplayFor(model => model.Skype)
                </div>
            </div>
        </div>
    }
</div>
}

ElderLists/ElderLists/Views/Users/Details.cshtml
@model ElderLists.Models.UserDetailsViewModel
@using ElderLists.Extensions
@{
    ViewBag.Title = "Пользователь";
    bool admin = User.IsInRole("Admin");
}

<h2>@ViewBag.Title</h2>
<hr />
<div class="form-horizontal">
    <h3>Личные данные</h3>
    <div class="form-group">
        @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-6">
            <div class="form-control-static">
                @Html.DisplayFor(model => model.UserName)
            </div>
        </div>
    </div>

    @if (Model.Email != null)
    {
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                <div class="form-control-static">
                    @Html.DisplayFor(model => model.Email)
                    @if (Model.IsEmailHidden)
                    {
                        @:<i>&emsp;(скрыт)</i>
                    }
                </div>
            </div>
        </div>
    }

    @if (admin)
    {
        <div class="form-group">
            <div class="col-md-offset-2 col-md-6">
                @Html.ActionLink("Изменить пароль", "ChangeUserPassword", "Manage", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-default"})
                @Html.ActionLink("Удалить пользователя", "DeleteUser", "Manage", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-default" })
            </div>
        </div>
    }

    <div class="form-group">
        @Html.LabelFor(model => model.Roles, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-6">
            <div class="form-control-static">
                @foreach (var role in Model.Roles)
                {
                    <p>@Html.DisplayFor(roleName => role)</p>
                }
                @if (admin)
                {
                    <p>
                    @if (Model.IsUser)
                    {
                        @Html.ActionLink("Лишить прав пользователя", "Discharge", "Users", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-default" })
                    }
                    else
                    {
                        @Html.ActionLink("Наделить правами пользователя", "Charge", "Users", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-default" })
                    }
                    </p>
                    <p>
                    @if (Model.IsModerator)
                    {
                        @Html.ActionLink("Лишить прав модератора", "Discharge", "Moderation", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-default" })
                    }
                    else
                    {
                        @Html.ActionLink("Наделить правами модератора", "Charge", "Moderation", new { id = Model.Id }, htmlAttributes: new { @class = "btn btn-default" })
                    }
                    </p>
                }
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RegisterDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-6">
            <div class="form-control-static">
                @Html.DisplayFor(model => model.RegisterDate)
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastAction, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-6">
            <div class="form-control-static">
                @Html.DisplayFor(model => model.LastAction)
            </div>
        </div>
    </div>
</div>

@if (Model.About != null)
{
    <div class="form-horizontal">
        <h3>Обо мне</h3>
        <div class="form-group">
            @Html.LabelFor(model => model.About, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                <div class="form-control-static">
                    @Html.DisplayMultilineFor(model => model.About)
                </div>
            </div>
        </div>
    </div>
}

@Html.Partial("Contacts", Model.Contacts)

@if (Model.Characters != null)
{
    @Html.Partial("Characters", Model.Characters)
}
@if (Model.Issues != null)
{
    @Html.Partial("Issues", Model.Issues)
}

ElderLists/ElderLists/Views/Users/Index.cshtml
@model IEnumerable<ElderLists.Models.UserListItemViewModel>

@{
    ViewBag.Title = "Пользователи";
}

<h2>@ViewBag.Title</h2>
@if (User.Identity.IsAuthenticated)
{
    <p>
        @Html.ActionLink("Моя страница", "My", "Users", routeValues: null, htmlAttributes: new { @class = "btn btn-default" })
        @if (User.IsInRole("Moderator") || User.IsInRole("Admin"))
        {
            @Html.ActionLink("Модераторы", "Moderators", "Users", routeValues: null, htmlAttributes: new { @class = "btn btn-default" })
        }
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Characters)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HiddenCharacters)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastAction)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Characters)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HiddenCharacters)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastAction)
            </td>
            <td>
                @Html.ActionLink("Подробнее", "Details", "Users", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-default" })
            </td>
        </tr>
    }

</table>

ElderLists/ElderLists/Views/Users/Issues.cshtml
@model IEnumerable<ElderLists.Models.ModerationIssueListItemViewModel>

<h3>Замечания</h3>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Target)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.State)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastReview)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(model => item.Target)
            </td>
            <td>
                @Html.DisplayFor(model => item.State)
            </td>
            <td>
                @Html.DisplayFor(model => item.LastReview)
            </td>
            <th>  
                @Html.ActionLink("Подробнее", "Details", item.TargetController, new { id = item.TargetId }, htmlAttributes: new { @class = "btn btn-default" })
            </th>
        </tr>
    }
</table>

ElderLists/ElderLists/Views/Users/Moderators.cshtml
@model IEnumerable<ElderLists.Models.UserModeratorListItemViewModel>

@{
    ViewBag.Title = "Модераторы";
}

<h2>@ViewBag.Title</h2>
@if (User.Identity.IsAuthenticated)
{
    <p>
        @Html.ActionLink("Моя страница", "My", "Users", routeValues: null, htmlAttributes: new { @class = "btn btn-default" })
        @Html.ActionLink("Все пользователи", "Index", "Users", routeValues: null, htmlAttributes: new { @class = "btn btn-default" })
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Issues)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OpenIssues)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastAction)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Issues)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OpenIssues)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastAction)
            </td>
            <td>
                @Html.ActionLink("Подробнее", "Details", "Users", new { id = item.Id }, htmlAttributes: new { @class = "btn btn-default" })
            </td>
        </tr>
    }

</table>